#!/usr/bin/env node
// jshint node: true
'use strict';
var newVersion = process.argv[2],
    fs = require('fs'),
    exec = require('child_process').exec,
    spawn = require('child_process').spawn,
    bowerJson = require('./bower.json');

if(!/^[0-9]+\.[0-9]+\.[0-9]+$/.test(newVersion)){
    console.error('Invalid version', newVersion);
    return process.exit(1);
}

console.log('tagging version', newVersion);

bowerJson.version = newVersion;

fs.writeFileSync('./bower.json', JSON.stringify(bowerJson, null, 2));

exec('git commit -am "v' + newVersion + '"', function(code){
    if(code > 0){
        console.error('Could not commit new version');
        return process.exit(1);
    }
    spawn('git', ['tag', 'v' + newVersion], {stdio: 'inherit'});
});
